const mongoose = require('mongoose');

const orderItemSchema = new mongoose.Schema({
  product: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true
  },
  name: {
    type: String,
    required: true
  },
  image: {
    type: String,
    required: true
  },
  price: {
    type: Number,
    required: true
  },
  quantity: {
    type: Number,
    required: true,
    min: [1, 'Quantity must be at least 1']
  }
});

const shippingAddressSchema = new mongoose.Schema({
  fullName: {
    type: String,
    required: true
  },
  address: {
    type: String,
    required: true
  },
  city: {
    type: String,
    required: true
  },
  district: {
    type: String,
    required: false,
    default: ''
  },
  ward: {
    type: String,
    required: true
  },
  phoneNumber: {
    type: String,
    required: true
  }
});

const orderSchema = new mongoose.Schema({
  orderNumber: {
    type: String,
    required: false // Auto-generated by pre-save hook
  },
  orderType: {
    type: String,
    required: true,
    enum: ['repair-service', 'parts-purchase'],
    default: 'repair-service'
  },
  repairInfo: {
    deviceType: {
      type: String,
      enum: ['iphone', 'ipad', 'android', 'tablet', 'other']
    },
    issue: {
      type: String,
      enum: ['screen', 'battery', 'charging', 'camera', 'speaker', 'button', 'water-damage', 'diagnosis', 'other']
    },
    issueDescription: String,
    appointmentDate: Date,
    estimatedCost: Number,
    estimatedDuration: String 
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  customerInfo: {
    name: {
      type: String,
      required: true
    },
    email: {
      type: String,
      required: true
    },
    phone: {
      type: String,
      required: true
    }
  },
  orderItems: {
    type: [orderItemSchema],
    default: [] 
  },
  shippingAddress: shippingAddressSchema,
  status: {
    type: String,
    required: true,
    enum: ['Chờ xác nhận', 'Đang xử lý', 'Hoàn thành', 'Hủy'],
    default: 'Chờ xác nhận'
  }
}, {
  timestamps: true
});

orderSchema.pre('save', async function(next) {
  if (!this.orderNumber) {
    const count = await this.constructor.countDocuments();
    this.orderNumber = `ORD${String(count + 1).padStart(6, '0')}`;
  }
  next();
});

orderSchema.index({ orderNumber: 1 }, { unique: true });
orderSchema.index({ status: 1 });
orderSchema.index({ createdAt: -1 });
orderSchema.index({ 'customerInfo.email': 1 });

module.exports = mongoose.model('Order', orderSchema);